### ISSUE TITLE
[Bug] 3D Touch Option Not Working.

### ISSUE THREAD

**Issue by iDonev** [NoisyFlake/ShortcutEnabler#2]
Hello!

First of all, thank you for the awesome tweak!

I would like to report that the option to activate the lock screen shortcuts using 3D Touch doesn't appear to be working correctly. I have seen similar complaints on reddit, so I don't think that I'm an isolated case. If I disable the 3D Touch requirement, then I can tap on the shortcuts and they work. Can you please look into this issue? Thanks!

Best Regards,
Iskren

PS: Below is a full list of installed tweaks and my device/iOS version:

Device: iPhone 7 Plus
iOS: 12.0

Tweaks:

AppCrumb: 1.0
AppList: 1.5.15 beta1
APT (apt-key): 1.4.9-2
APT 1.4 Strict (libapt-pkg): 1.4.9-1
APT Strict (lib): 1.4.9-2
APT Strict: 1.4.9-1
Assuan: 2.5.1-1
AudioSnapshotServer: 1.0.1
Base Structure: 1-5
Berkeley DB: 6.2.32-1
BigBoss Icon Set: 1.0
Bourne-Again SHell: 5.0.3-1
bzip2: 1.0.6-1
CA Certs: 0.0.2
CCSupport: 1.2-3
Cephei: 1.13.1-2
Core Utilities (/bin): 8.30-3
Core Utilities: 8.30-2
Cydia Installer: 1.1.32 b16
Cydia Substrate: 0.9.7033
Cydia Translations: 1.1.32 b1
Darwin Tools: 1-6
Debian Packager: 1.18.25-11
Debian Utilities: 4.8.6-1
Diff Utilities: 3.6-1
diskdev-cmds: 593.221.1-1
DontKillMyMusic: 1.3.1
Essential: 0-1
file: 5.35-2
Find Utilities: 4.6.0-2
Flame: 1.3
gettext: 0.19.8-1
GNU Cryptography: 1.8.3-1
GNU Multiple Precision Arithmetic Library: 6.1.2-1
GnuPG Errors: 1.32-1
GnuPG: 2.2.11-2
GnuTLS: 3.5.19-1
grep: 3.1-1
gzip: 1.9-1
IconSupport: 1.11.1
iOS Firmware: 12.0
iPhone Firmware (/sbin): 0-1
Jailbreak Resources: 1.0 b23
KSBA: 1.3.5-1
LetMeBlock: 0.0.6.8
libcolorpicker-nepeta: 1.6.2-3
libidn2: 6.1.2-1
libmitsuha: 0.1.9
libnepeta: 0.1.1
libpackageinfo: 1.1.0.1-1
libplist: 2.0.0-2
libSubstitrate: 0.0.1-3
libtasn1: 4.13-1
libunistring: 0.9.10-1
Link Identity Editor: 2:2.1.1+elucubratus2
LittleXS: 2.2.0
LuxSit: 1.0
LZ4: 1.7.5-1
LZMA Utils: 2:4.32.7-2
Mitsuha Infinity - Home Screen: 0.1.1
Mitsuha Infinity: 0.1.6
Nettle: 3.4.1-1
New Curses: 5.9-1
New Curses: 6.1-1
New GNU Portable Threads: 1.6-1
OhMyFlash: 1.0.0
OpenSSH: 7.9p1-3
OpenSSL 1.0 Libraries: 1.0.2s-1
p11-kit: 0.23.12-1
PreferenceLoader: 2.2.4 beta1
Profile Directory: 0-1
readline: 8.0-1
RocketBootstrap: 1.0.7 beta3
Screender: 1.0.2
sed: 4.5-1
shell-cmds: 118-8
Shenmue: 1.0
ShortcutEnabler: 1.1.4
Signing Certificate: 0.0.1
Substrate Safe Mode: 0.9.6001.1
SugarCane12: 1.0.0-1+debug
System Memory Reset Fix: 1.0
system-cmds: 790.30.1-2
Tape Archive: 1.30-2
TechSupport Framework: 1.5.0.1-1
Trust Cache Injector: 0.4 b5
UIKit Tools: 1.1.13-18
VideoSwipes: 1.3
XZ Utils: 5.2.4-4
Zenith: 1.1.1-2

**Comment by NoisyFlake** [comment]
It looks like this is a problem with iOS 12.0, as nobody on 12.1 or higher had this problem so far. Apple probably changed the way 3D touch works in 12.1, but as I don't have any device left on 12.0, there's no way for me to test and fix this.
